#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker03"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "1c12c7a33f074dde8f406e5924603d0a" }
]

[assets]
directory = "./public"
